name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer

    - name: Validate PHP syntax
      run: find . -type f -name "*.php" -exec php -l {} \;

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist

    - name: Run tests
      run: vendor/bin/phpunit

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Deploy to Production
      run: |
        echo "Deploying to production server"
        # Contoh perintah deploy, ganti dengan yang sesuai
        ssh user@server "cd /path/to/your/app && git pull origin main && composer install --no-dev && php artisan migrate"
