name: PHPUnit

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '10.5'
        
    - name: Install dependencies
      run: composer install
      
    - name: Run PHPUnit tests
      run: |
        wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
        chmod +x phpunit
        ./phpunit
